### ISSUE TITLE
Support schema evolution

### ISSUE THREAD

**Issue by vitillo** [mozilla/telemetry-streaming#19]
Ideally we would like to have a generic mechanism in which we declare a metric part of the dashboard, which could be an annotation in the metric definition files. In order to support this use-case, we have to verify if it's possible to change the schema of the data being aggregated at run-time. If that fails, we should verify that to the very least the checkpointing logic works as expected when redeploying the application with an updated schema definition.

**Comment by maurodoglio** [comment]
I verified this works without apparent issues. The only downside is that consumers of the parquet partition need to allow schema merging, but that's a fair requirement. [Here](https://gist.github.com/maurodoglio/5eb993cb3ed42157c0bf9cb19f65800a) is a gist of the notebook I used to test this.
