### ISSUE TITLE
Add a "hangs per minute" count

### ISSUE THREAD

**Issue by chutten** [mozilla/telemetry-streaming#20]
From @digitarald, a nice measure of release health would be the number of hangs > 100ms experienced by users, broken down by process. It can be divided by usage_hours*60 to get to our familiar "hangs per minute" number (though possibly with a decreased precision. PMs may wish to change this to a measure like "hangs per kilo-usage-hour").

**Comment by mikeconley** [comment]
Getting a sense of the health is useful, but it's also useful to drill down to see what's causing a certain measurement of health. Being able to split out the hangs into their individual stack signatures would be useful.

**Comment by digitarald** [comment]
RelMan need to track this number on a continues basis as a release health. We also have hangs as as release criteria.

Dimensions should be mostly carried over from https://github.com/mozilla/telemetry-batch-view/blob/master/docs/CrashAggregateView.md but can be simplified.

**Comment by maurodoglio** [comment]
@mikeconley telemetry doesn't collect/generate stack signatures yet, but ddurst's team is working on it. Once that's done we will likely add it to the [war room](https://docs.google.com/a/mozilla.com/document/d/1SgpqUXnOLCakx5HdDoLkv83Pt4iNUxeQMfV0iQ3fqBo/edit?usp=sharing) dashboard.

**Comment by digitarald** [comment]
@maurodoglio the raw hang data in telemetry  has signatures. can you clarify where we don't have stacks/signatures it. There might be work going on that we don't know about :)

**Comment by maurodoglio** [comment]
I'm probably confusing crashes and hangs here. I was talking about the effort described [here](https://docs.google.com/document/d/158pdT9K3JFjIxOLO-zrKrM20KbT_stFmcuH9ctPVvsw/edit#heading=h.ih0k2u90sp4f). Sorry for the noise.

**Comment by digitarald** [comment]
Related https://bugzilla.mozilla.org/show_bug.cgi?id=1344003

**Comment by digitarald** [comment]
@maurodoglio will we have something up for this by end of Q1?

**Comment by maurodoglio** [comment]
No, [here](https://docs.google.com/a/mozilla.com/document/d/1SgpqUXnOLCakx5HdDoLkv83Pt4iNUxeQMfV0iQ3fqBo/edit?usp=sharing) is the roadmap for this project. According to it this is going to happen in Q2

**Comment by digitarald** [comment]
Posted https://bugzilla.mozilla.org/show_bug.cgi?id=1346865 for roadmapping

**Comment by maurodoglio** [comment]
I'm closing this issue accordingly to [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1346865#c5)
