### ISSUE TITLE
Remove catch-all try statements

### ISSUE THREAD

**Issue by fbertsch** [mozilla/telemetry-streaming#85]
We use these to prevent malformed pings from breaking the dataset creation, but it can have unexpected side effects (e.g. catching OOM errors). We should figure out what exceptions we expect, add tests for them, and catch them specifically.

**Comment by akkomar** [comment]
How about [NonFatal extractor](https://www.scala-lang.org/api/current/scala/util/control/NonFatal$.html) as a first step? It would prevent from catching JVM-level errors.
